=== Nikitondri/epamtasks/task07xml/src/main/resources/xml/reviews.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://zakharenko.by/task07xml/entity/reviews"
        xmlns:tns="http://zakharenko.by/task07xml/entity/reviews"
        elementFormDefault="qualified" attributeFormDefault="qualified">
    <element name="reviews">
        <complexType>
            <sequence>
                <element name="review"
                         type="tns:Review"
                         minOccurs="5"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Review">
        <sequence>
            <element name="id" type="long"/>
            <element name="dish" type="tns:Dish"/>
            <element name="user" type="tns:User"/>
            <element name="parentId" type="int"/>
            <element name="text" type="string"/>
            <element name="createDate" type="dateTime"/>
        </sequence>
    </complexType>
    <complexType name="Dish">
        <sequence>
            <element name="dishId" type="int"/>
            <element name="name" type="string"/>
            <element name="cost" type="double"/>
            <element name="type" type="tns:DishType"/>
            <element name="weight" type="int"/>
            <element name="description" type="string"/>
            <element name="picturePath" type="string"/>
        </sequence>
        <attribute name="isEnable" type="tns:IsEnable" default="1" form="unqualified"/>
    </complexType>
    <complexType name="User">
        <all>
            <element name="userId" type="long"/>
            <element name="login" type="string"/>
            <element name="password" type="string"/>
<!--            <element name="status" type="tns:Status"/>-->
        </all>
        <attribute name="role" type="tns:RoleType" use="required" form="unqualified"/>
        <attribute name="status" type="tns:Status" default="1" form="unqualified"/>
    </complexType>
    <complexType name="DishType">
        <sequence>
            <element name="typeId" type="int"/>
            <element name="typeName" type="string"/>
        </sequence>
    </complexType>

    <simpleType name="RoleType">
        <restriction base="string">
            <enumeration value="CLIENT"/>
            <enumeration value="ADMIN"/>
            <enumeration value="WORKER"/>
        </restriction>
    </simpleType>
    <simpleType name="Status">
        <restriction base="int">
            <enumeration value="0"/>
            <enumeration value="1"/>
        </restriction>
    </simpleType>
    <simpleType name="IsEnable">
        <restriction base="int">
            <enumeration value="0"/>
            <enumeration value="1"/>
        </restriction>
    </simpleType>
</schema>

=== Nikitondri/epamtasks/task07xml/src/test/resources/xml_files/reviews3.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<reviews xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://zakharenko.by/task07xml/entity/reviews"
         xsi:schemaLocation="http://zakharenko.by/task07xml/entity/reviews reviews.xsd">
    <review>
        <id>1</id>
        <dish isEnable="0">
            <dishId>1</dishId>
            <name>Паста Порчини</name>
            <cost>12.4</cost>
            <type>
                <typeId>1</typeId>
                <typeName>main</typeName>
            </type>
            <weight>300</weight>
            <description>Паста с белыми грибами</description>
            <picturePath>none</picturePath>
        </dish>
        <user role="CLIENT">
            <userId>2</userId>
            <login>login2</login>
            <password>password2</password>
        </user>
        <parentId>0</parentId>
        <text>Вкусно!</text>
        <createDate>2022-02-03T13:23:12</createDate>
    </review>
    <review>
        <id>2</id>
        <dish isEnable="0">
            <dishId>1</dishId>
            <name>Паста Порчини</name>
            <cost>12.4</cost>
            <type>
                <typeId>1</typeId>
                <typeName>main</typeName>
            </type>
            <weight>300</weight>
            <description>Паста с белыми грибами</description>
            <picturePath>none</picturePath>
        </dish>
        <user role="ADMIN">
            <userId>1</userId>
            <login>login1</login>
            <password>password1</password>
        </user>
        <parentId>1</parentId>
        <text>Спасибо за отзыв!</text>
        <createDate>2022-02-03T15:13:00</createDate>
    </review>
    <review>
        <id>3</id>
        <dish>
            <dishId>2</dishId>
            <name>Маргарита</name>
            <cost>9.6</cost>
            <type>
                <typeId>2</typeId>
                <typeName>pizza</typeName>
            </type>
            <weight>540</weight>
            <description>Соус из протертых томатов, Моцарелла</description>
            <picturePath>NONE</picturePath>
        </dish>
        <user role="CLIENT">
            <userId>3</userId>
            <password>password3</password>
            <login>login3</login>
        </user>
        <parentId>0</parentId>
        <text>Хорошая пицца!</text>
        <createDate>2022-03-03T20:22:52</createDate>
    </review>
</reviews>
